### ISSUE TITLE
<condition>文法的疑问

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-handbook#1]
在指导书中`<condition> ::= <expression>[<relationa-operator><expression>]`

1. 对于简单的`<condition> ::= <expression>`
表达式`<expression>`推导到最后结果一定是`<identifier>|<integer-literal>|<function-call>`这三者之一或者它们的组合，但无论如何`expression`的计算结果肯定是C0中的某一种类型。可现有的类型系统没有可供条件判断所需要的布尔类型，所以只能在语义上进行基础类型到布尔类型的转换，比如`if (0)`和`if (false)`是等价的，那么具体的规则是什么呢？

2. 对于`<expression><relational-operator><expression>`
`<relational-operator>`提供了布尔的语义，所以这个是可以作为条件判断的

**Comment by fazdzz** [comment]
应当是和C一样，0是false，其他都是true

**Comment by fazdzz** [comment]
[最新的commit](https://github.com/BUAA-SE-Compiling/c0-handbook/commit/c9f72ad65ecf65d3db4ec850694932907c6140ef) 不知道有没有解决您的问题

**Comment by fazdzz** [comment]
补充说明一下，虚拟机提供了两套判断这种条件的方法。
第一种是用sub系列的指令算结果，然后用je（栈顶是0）、jl（栈顶是负数）、jg（栈顶是正数）之类的跳转
第二种是用cmp系列的指令判断（结果是0或1或-1），然后用je、jl、jg之类的跳转。

**Comment by Zx55** [comment]
好的
