### ISSUE TITLE
关于可接受字符集的小建议

### ISSUE THREAD

**Issue by Anthony6075** [BUAA-SE-Compiling/c0-handbook#2]
C0的可接受字符集中包括32种标点字符：_ ( ) [ ] { } < = > . , : ; ! ? + - * / % ^ & | ~ \ " ' ` $ # @，即便是对于扩展的C0，它们中一部分也没有在产生式的右侧出现过，这些字符放到可接受字符集中是不是有些不合适呢？

**Comment by fazdzz** [comment]
[指导书中有关字符串字面量的内容](https://github.com/BUAA-SE-Compiling/c0-handbook#3232-%E5%AD%97%E7%AC%A6%E5%AD%97%E9%9D%A2%E9%87%8F%E4%B8%8E%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AD%97%E9%9D%A2%E9%87%8F)
