### ISSUE TITLE
switch语句文法的建议

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-handbook#4]
指导书中[switch文法](https://github.com/BUAA-SE-Compiling/c0-handbook/blame/580a757f93c2298434d9cd5eebaf1c9d14093722/README.md#L1396)如下
`<switch-stmt> ::= 'switch' '(' <cond> ')' '{' {<labeled-stmt>} '}'`
其中条件`<cond> ::= <expr>[<relation-op><expr>]`

我的想法是`<cond>`更加强调的是布尔的结果，true or false
这显然不是switch语句的主要功能，仅仅是switch (true or false)，那么为什么不用if-else呢？

我觉得改为`<switch-stmt> ::= 'switch' '(' <expr> ')' '{' {<labeled-stmt>} '}'`更为合理
这里`<expr>`强调的是求值结果，然后去和`<labeled-stmt>`进行匹配

尽管switch语句里可以使用`<cond>`；类比一下`<assignment>`在C语言中也可以使用条件进行赋值
如`int a = 1 > 0;`，那似乎`<assignment> ::= <cond>`更好不是吗？因为`<cond>`也包括了`<expr>`的情况

再者尽管[指导书](https://github.com/BUAA-SE-Compiling/c0-handbook/blame/580a757f93c2298434d9cd5eebaf1c9d14093722/README.md#L313)指出了`<cond>`转换到布尔的情况，但也明确指出了其表达式求值结果的不确定性，例如
```c
switch (1 > 0) {
    case 1: // ...
    case 2: // ...
}
```
这本身就是一个UB，因为1>0的最终值是一个UB

**Comment by Zx55** [comment]
另外：如果进行了不等价的文法改写（如上面这种情况）并且在文档中进行了说明，会对最终评分有影响吗？

**Comment by fazdzz** [comment]
指导书有错，`<switch>` 里的应该是 `<expr>` 而不是 `<cond>`

**Comment by fazdzz** [comment]
> 另外：如果进行了不等价的文法改写（如上面这种情况）并且在文档中进行了说明，会对最终评分有影响吗？

不确定性因素较多，不过因为是当场跑用例，真出问题了还得看怎么解释和实际情况
