### ISSUE TITLE
Typo Report

### ISSUE THREAD

**Issue by yiranyyu** [BUAA-SE-Compiling/c0-handbook#5]
[这里](https://github.com/BUAA-SE-Compiling/c0-handbook/blame/cc4067c08b13e925dd550f53461407a4f7f76c67/README.md#L1146)

原文：
> 如果你提供一个**编译器**来存储你预读的输入，至少可以避免多次分析同一输入。与之共存的问题还有：缓冲区开多大合适？具体如何维护？

是不是应该是：
> 如果你提供一个**缓冲区**来存储你预读的输入，至少可以避免多次分析同一输入。与之共存的问题还有：缓冲区开多大合适？具体如何维护？

或者说是我理解错了 orz

**Comment by fazdzz** [comment]
typo
