### ISSUE TITLE
void不参与计算的意思是不能转换为void？

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-handbook#6]
void肯定不能转换成其他类型，但是反过来其他类型可以转换成void吗？

比如
```
int add(int a, int b) { return a + b; }

int main() {
    (void) add(1, 2);
    (void) (1 + 2);
}
```
类似这样的代码在c0中是否合法？

还有种情况void转换成void怎么处理？ orz

**Comment by fazdzz** [comment]
> void不参与计算的意思是不能转换为void？

意思是想说 `void` 本身没有值语义，所以`<primary-expr>` 的类型不能是 `void` （感觉这样说会清楚一点，一会儿改一下），比如 void+T、void*T、void == T 这些都不行

> void肯定不能转换成其他类型，但是反过来其他类型可以转换成void吗？

同样因为void本身没有值语义，在我们这里是UB。

> ```c
> int add(int a, int b) { return a + b; }
> 
> int main() {
>     (void) add(1, 2);
>     (void) (1 + 2);
> }
> ```
> 
> 类似这样的代码在c0中是否合法？

不合法，不是因为UB，而是因为C0的 `<statement>` 不能是 `<expression>`

> 还有种情况void转换成void怎么处理？ orz

~~因为是UB，不考虑~~

**Comment by fazdzz** [comment]
感觉 C0 的内容组织顺序不太合理，之后考虑重排一下

**Comment by fazdzz** [comment]
补充：

因为`void`没有值语义，因此从`void`转换到其他有值语义的类型是不合法的

`void`到`void`从定义上来看没什么问题，因为两者都没有值语义。但是这么做没什么意义（不会有任何实际的语义动作发生），和其他类型到`void`一视同仁当作UB也可以。这个东西之后会论证一下，总之不会测这个。

**Comment by Zx55** [comment]
> 感觉 C0 的内容组织顺序不太合理，之后考虑重排一下

类型转换感觉写的有点分散 如果能统一在一个地方给全部转换规则就好了

**Comment by Zx55** [comment]
又看了下文法
```
<cast-expression> ::=
    {'('<type-specifier>')'}<unary-expression>
<unary-expression> ::=
    [<unary-operator>]<primary-expression>
```
cast推导到最后右侧肯定是`<primary-expr>`，这个已经限定不是void了
那么肯定不会发生从void到任何类型的转换，因为`<prim-expr>`产生了void本身已经是不合法的

而简单类型（除void）转换到void，尽管就`<cast-expr>`来说似乎没什么问题
但是最后这个`<cast-expr>`是要进行计算的，void还是会报错
（主要是这边如果默认能转换到void的话，已经压入栈的`<primary-expr>`必须用pop指令弹栈，因为void没有值；这样处理就比较麻烦，考虑到最终都会报错，这里纠结pop就显得无用功）

所以我想直接`<cast>`就不允许void到任何类型的转换，也不允许任何类型到void的转换，所有都报错

**Comment by fazdzz** [comment]
> 不允许void到任何类型的转换，也不允许任何类型到void的转换

是个办法。

总结一下就还是void类型不能参与求值：从void到其他类型，这里是参与cast-expr求值的表达式类型是void，此时有错误；从其他类型到void，是求值后的cast-expr类型是void，当其参与更高等级的运算或赋值时就会发生错误。

说到头是对表达式这个东西的语义没有进行充分的解释。

这些内容和现在的指导书都是没有冲突的，就是需要换个描述方式。
