### ISSUE TITLE
关于<conditon>的运算数和<assignment-expression>右侧不能有函数名的疑惑

### ISSUE THREAD

**Issue by Zx55** [BUAA-SE-Compiling/c0-handbook#7]
> [指定书中关于`<condition>`的说明](https://github.com/BUAA-SE-Compiling/c0-handbook/blame/836224bccdcfaae2a782705f700a937233b1f408/README.md#L310)
> [指导书中关于`<assignment-express>`的说明](https://github.com/BUAA-SE-Compiling/c0-handbook/blame/836224bccdcfaae2a782705f700a937233b1f408/README.md#L315)

这意味着不能用函数调用来进行计算？即使是非 void 返回值的函数也不行吗？
比如以下代码是否是不符合语义的呢？因为`<cond>`和`<assign>`中出现了函数名
```c
int foo() { return 1; }
int main() {
    int a = foo() + 1;
    if (a > foo()) {
        print(a);
    }
    return 0;
}
```
**还是说这里仅仅在强调不能将函数标识符当做一个变量来使用？**

**Comment by fazdzz** [comment]
> 还是说这里仅仅在强调不能将函数标识符当做一个变量来使用？

T

**Comment by Zx55** [comment]
好的
