### ISSUE TITLE
Typo Report

### ISSUE THREAD

**Issue by yiranyyu** [BUAA-SE-Compiling/c0-handbook#8]
[这里](https://github.com/BUAA-SE-Compiling/c0-handbook/blame/836224bccdcfaae2a782705f700a937233b1f408/README.md#L307)直接说**取负**是不是有问题，毕竟还有 `+` 这个单目运算符。感觉是 typo

> 对于单目的算术表达式（`<unary-expression>`），其类型和操作数（`<primary-expression>`）相同，值等同于对操作数进行算术取负的结果

**Comment by fazdzz** [comment]
确实
